### ISSUE TITLE
Adding prompt engineering with llama3 

### ISSUE THREAD

**Issue by Gitstar-OC** [meta-llama/llama3#199]
Hello, I have just caught up with the prompt engineering model with llama3 and have a Idea if I should make a commit to the read me file or add a readme file, or jupyter notebook here to get people started with making short model?

**Comment by Gitstar-OC** [comment]
Basically I have completed the whole prompt engineering stuff with llama3 which can be used to create your own chat model inside your own pc or computer. I could upload how to do it by a jupyter notebook or a markdown file to help new learners to make their own chat model with the help of the llama! Should I create a pull request for notebook or readme file? Reply me

**Comment by DragonAngel1st** [comment]
I would love to look at your code. I've been working on understanding why I can't load my vanilla Llama 3 model straight into Langchain and why would I need to convert it and quantize it. I'm trying learn this by myself and it's quite slow because there is not much out there. So cheers if you can do a pull request, I would certainly try it out. There are many ways you can use ollama and huggingface but nothing about creating your own API... 
Patrick Miron

**Comment by Gitstar-OC** [comment]
Great I will make a pull request today, closing this issue. Thanks for your reply!
