### ISSUE TITLE
Request to Add Prompt Details for Trivia QA Evaluation to Make Scores Reproducible

### ISSUE THREAD

**Issue by jasonkrone** [meta-llama/llama3#279]
A few folks, including me, have been [trying and failing](https://github.com/EleutherAI/lm-evaluation-harness/issues/1292) to reproduce the llama Trivia QA scores using the [Eluther Evaluation Harness](https://github.com/EleutherAI/lm-evaluation-harness). Specifically, for llama 3 8B I'm getting an EM score of 74.0% vs. the [78.5% reported on the huggingface llama3 page](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B). 

@rohit-ptl would it be possible to add details on the prompt used for llama3 Trivia QA evaluation? If there are other details on Trivia QA eval that have a big impact, it would be great to note those as well. 

Currently the evaluation harness is using the following prompt: "Question: {{question}}?\nAnswer:"

**Comment by wukaixingxp** [comment]
Hi! Thanks for your question! We used our internal eval implementation to generate those metrics instead of relying on the public [lm_evaluation_harness](https://github.com/EleutherAI/lm-evaluation-harness) library. Here is a summary of our [eval details](https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/eval_details.md#language-auto-eval-benchmark-notes) and we also published the evaluation result details as datasets in the [Llama 3.1 Evals](https://huggingface.co/collections/meta-llama/llama-31-evals-66a2c5a14c2093e58298ac7f) Hugging Face collections for you to review. I believe [this detail](https://huggingface.co/datasets/meta-llama/Meta-Llama-3.1-8B-evals/viewer/Meta-Llama-3.1-8B-evals__triviaqa__wiki__details) may help you.

**Comment by jasonkrone** [comment]
This is super helpful! Thank you, Kai!
