### ISSUE TITLE
llama3-1-8B performing poorly on leader board

### ISSUE THREAD

**Issue by sorobedio** [meta-llama/llama3#297]
which command did you use to  produce the results on the leaderboard.
 i tried this command: 
`lm_eval --model hf \
    --model_args pretrained=meta-llama/Meta-Llama-3.1-8B,dtype="bfloat16"\
    --tasks leaderboard_gpqa\
    --device cuda:0 \
    --num_fewshot 0\
    --apply_chat_template\
    --batch_size auto:2`
 And got these raw scores .

|           Tasks            |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|----------------------------|-------|------|-----:|--------|---|-----:|---|-----:|
|leaderboard_gpqa            |    N/A|      |      |        |   |      |   |      |
| - leaderboard_gpqa_diamond |      1|none  |     0|acc_norm|↑  |0.2778|±  |0.0319|
| - leaderboard_gpqa_extended|      1|none  |     0|acc_norm|↑  |0.2491|±  |0.0185|
| - leaderboard_gpqa_main    |      1|none  |     0|acc_norm|↑  |0.2612|±  |0.0208|

 and with musr task I got.
|                Tasks                |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|-------------------------------------|-------|------|-----:|--------|---|-----:|---|-----:|
|leaderboard_musr                     |    N/A|      |      |        |   |      |   |      |
| - leaderboard_musr_murder_mysteries |      1|none  |     0|acc_norm|↑  |0.5040|±  |0.0317|
| - leaderboard_musr_object_placements|      1|none  |     0|acc_norm|↑  |0.2305|±  |0.0264|
| - leaderboard_musr_team_allocation  |      1|none  |     0|acc_norm|↑  |0.2800|±  |0.0285|

how to properly evaluate llama3-1-8B

**Comment by wukaixingxp** [comment]
Hi! Thanks for your question! We used our internal eval implementation to generate those metrics instead of relying on the public [lm_evaluation_harness](https://github.com/EleutherAI/lm-evaluation-harness) library. Here is a summary of our [eval details](https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/eval_details.md#language-auto-eval-benchmark-notes) and we also published the evaluation result details as datasets in the [Llama 3.1 Evals](https://huggingface.co/collections/meta-llama/llama-31-evals-66a2c5a14c2093e58298ac7f) Hugging Face collections for you to review.

**Comment by sherlcok314159** [comment]
I guess that you used the wrong model for evaluation. According to the Llama3.1-Evals, they use `Instruct` model instead of the backbone. When I run the evaluation with instruct model (8B), the results look fine.

|           Tasks            |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|----------------------------|-------|------|-----:|--------|---|-----:|---|-----:|
|leaderboard_gpqa            |    N/A|      |      |        |   |      |   |      |
| - leaderboard_gpqa_diamond |      1|none  |     0|acc_norm|↑  |0.3636|±  |0.0343|
| - leaderboard_gpqa_extended|      1|none  |     0|acc_norm|↑  |0.3223|±  |0.0200|
| - leaderboard_gpqa_main    |      1|none  |     0|acc_norm|↑  |0.3214|±  |0.0221|

**Comment by sorobedio** [comment]
Thank you! For other cases with few-shot examples, I should also remove the chat-template arguments, correct?

**Comment by wukaixingxp** [comment]
@sorobedio  @sherlcok314159 We have developed a [eval reproduce recipe](https://github.com/meta-llama/llama-recipes/tree/main/tools/benchmarks/llm_eval_harness/meta_eval_reproduce) to run our published 3.1 evals Hugging Face datasets with [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness). Please take a look and hopefully it can be helpful to you.

**Comment by wukaixingxp** [comment]
There are some differences on our eval implementation and OpenLLM leaderboard v2 as stated in previous eval reproduce recipe, to reproduce the leaderboard result, please take a look at [this section](https://github.com/meta-llama/llama-recipes/tree/leaderboardv2/tools/benchmarks/llm_eval_harness#reproducing-huggingface-open-llm-leaderboard-v2)

**Comment by sorobedio** [comment]
thank you
